#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidCalculator.Resource", IsApplication=true)]

namespace AndroidCalculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001d
			public const int button0 = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int button1 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int button2 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int button3 = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int button4 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int button5 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int button6 = 2131034133;
			
			// aapt resource value: 0x7f05000e
			public const int button7 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int button8 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int button9 = 2131034128;
			
			// aapt resource value: 0x7f050016
			public const int buttonAdd = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int buttonAddToMemory = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int buttonClear = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int buttonClearMemory = 2131034116;
			
			// aapt resource value: 0x7f050024
			public const int buttonCosine = 2131034148;
			
			// aapt resource value: 0x7f05001e
			public const int buttonDecimalPoint = 2131034142;
			
			// aapt resource value: 0x7f05000b
			public const int buttonDivide = 2131034123;
			
			// aapt resource value: 0x7f05001f
			public const int buttonEquals = 2131034143;
			
			// aapt resource value: 0x7f050022
			public const int buttonInvert = 2131034146;
			
			// aapt resource value: 0x7f05000c
			public const int buttonMultiply = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int buttonRecallMemory = 2131034119;
			
			// aapt resource value: 0x7f050023
			public const int buttonSine = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int buttonSquareRoot = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int buttonSquared = 2131034145;
			
			// aapt resource value: 0x7f050011
			public const int buttonSubtract = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int buttonSubtractFromMemory = 2131034118;
			
			// aapt resource value: 0x7f050025
			public const int buttonTangent = 2131034149;
			
			// aapt resource value: 0x7f05000a
			public const int buttonToggleSign = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int functionPad = 2131034112;
			
			// aapt resource value: 0x7f050018
			public const int linearLayout1 = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int linearLayout2 = 2131034140;
			
			// aapt resource value: 0x7f050001
			public const int row1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int row2 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int row3 = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int row4 = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int row5 = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int row6 = 2131034135;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int action_settings = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int button0 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int button1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int button2 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int button3 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int button4 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int button5 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int button6 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int button7 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int button8 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int button9 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int buttonAdd = 2130968591;
			
			// aapt resource value: 0x7f040018
			public const int buttonAddToMemory = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int buttonClear = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int buttonClearMemory = 2130968599;
			
			// aapt resource value: 0x7f04001f
			public const int buttonCosine = 2130968607;
			
			// aapt resource value: 0x7f040014
			public const int buttonDecimalPoint = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int buttonDivide = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int buttonEquals = 2130968597;
			
			// aapt resource value: 0x7f04001d
			public const int buttonInvert = 2130968605;
			
			// aapt resource value: 0x7f040011
			public const int buttonMultiply = 2130968593;
			
			// aapt resource value: 0x7f04001a
			public const int buttonRecallMemory = 2130968602;
			
			// aapt resource value: 0x7f04001e
			public const int buttonSine = 2130968606;
			
			// aapt resource value: 0x7f04001b
			public const int buttonSquareRoot = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int buttonSquared = 2130968604;
			
			// aapt resource value: 0x7f040010
			public const int buttonSubtract = 2130968592;
			
			// aapt resource value: 0x7f040019
			public const int buttonSubtractFromMemory = 2130968601;
			
			// aapt resource value: 0x7f040020
			public const int buttonTangent = 2130968608;
			
			// aapt resource value: 0x7f040013
			public const int buttonToggleSign = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int menu_settings = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
